# Generated by Django 5.0.3 on 2024-05-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.TextField(unique=True)),
                ('team_fullname', models.TextField(blank=True, unique=True)),
                ('team_abbreviation', models.TextField(blank=True, unique=True)),
                ('league', models.TextField(default='nba')),
                ('discipline', models.TextField(default='basketball')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('outcome', models.BooleanField()),
                ('home_team_score', models.IntegerField(blank=True, null=True)),
                ('visitor_team_score', models.IntegerField(blank=True, null=True)),
                ('game_date', models.DateField()),
                ('away_team', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='away_team_game', to='Matches.teams')),
                ('home_team', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='home_team_game', to='Matches.teams')),
            ],
            options={
                'db_table': 'games_data',
            },
        ),
    ]
