# Generated by Django 5.0.3 on 2024-05-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team_abbreviation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_fullname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='gamedata',
            table='games_data',
        ),
        migrations.AlterModelTable(
            name='teams',
            table='teams',
        ),
    ]
