# Generated by Django 5.0.3 on 2024-05-23 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Matches', '0002_alter_teams_team_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'Tweets_contents',
            },
        ),
        migrations.CreateModel(
            name='TweetData',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('replyies', models.IntegerField(blank=True)),
                ('retweets', models.IntegerField(blank=True)),
                ('likes', models.IntegerField(blank=True)),
                ('views', models.IntegerField(blank=True)),
                ('content_id', models.OneToOneField(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, related_name='tweet_with_contents', to='Posts.tweetcontent')),
                ('related_game', models.OneToOneField(db_column='related_game', on_delete=django.db.models.deletion.CASCADE, to='Matches.gamedata')),
            ],
            options={
                'db_table': 'tweets_data',
            },
        ),
    ]
