# Generated by Django 5.0.3 on 2024-05-23 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0002_alter_teams_team_abbreviation_and_more'),
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdata',
            name='related_game',
            field=models.ForeignKey(db_column='related_game', on_delete=django.db.models.deletion.CASCADE, to='Matches.gamedata'),
        ),
    ]
